### ISSUE TITLE
Feedback/console

### ISSUE THREAD

**Issue by tokejepsen** [davidpaulrosser/atom-maya#3]
I was wondering whether there are any alternatives or something to make that is like a filtered console?

Atm the console where you get feedback from Maya, without having switch windows, gets cluttered with other outputs from various packages. So a filtered console where you only see the Maya output, or a more persistent message rather than the brief pop-up message about errors.

**Comment by davidpaulrosser** [comment]
It's a good idea and I'm more than happy if you have time to look into it. I try to keep my Maya console as clean as possible from other outputs but I imagine your using a lot more plugins than I am.

**Comment by tokejepsen** [comment]
There seems to be a package that can handle this with a bit of modification on this package; https://atom.io/packages/log-console.
It expects a log file, which Maya by default don't provide (?), but if this package would output its console.log calls (which are commented out?) to a file, we could just point to that.

Let me know what you think.

I dont know how the Eclipse plugin does it, but you get all script editor output into Eclipse which is what I'm looking for, for this.

**Comment by tokejepsen** [comment]
There is also this package that will make an output console; https://atom.io/packages/script. I'll investigate further on this.

**Comment by tokejepsen** [comment]
I've got a method for doing a message, which I have working in; https://github.com/tokejepsen/atom-foundry-nuke, with this commit; https://github.com/tokejepsen/atom-foundry-nuke/commit/b10306aec9d77e610877a6e2c3cced12dd6616f4

I wanted to do it for this as well, but I can't seem to get any stdout from Maya. Know anything about this?
