### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by Sosoyan** [davidpaulrosser/atom-maya#7]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `Maya` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:444:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:455:32)
Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:437:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:19)
```

**Comment by davidpaulrosser** [comment]
Fixed now in latest release.

**Comment by ma55acre** [comment]
Package.getStylesheetsPath - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:460:9
Package.getStylesheetPaths - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:471:32
Package.loadStylesheets - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:453:38
<unknown> - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:185:19
Package.measure - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15
Package.load - C:\Users\mmaus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:179:12
